### ISSUE TITLE
Downloads fail with a plethora of error messages

### ISSUE THREAD

**Issue by mrmatteastwood** [Dniel97/orpheusdl-tidal#23]
**Describe the bug**
Downloads fail. Here's what I tried, and the command line output:

```
~/Appdata/Linux-Apps/orpheusdl$ python orpheus.py https://tidal.com/browse/album/222863872/

   ____             _                    _____  _      
  / __ \           | |                  |  __ \| |     
 | |  | |_ __ _ __ | |__   ___ _   _ ___| |  | | |     
 | |  | | '__| '_ \| '_ \ / _ \ | | / __| |  | | |     
 | |__| | |  | |_) | | | |  __/ |_| \__ \ |__| | |____ 
  \____/|_|  | .__/|_| |_|\___|\__,_|___/_____/|______|
             | |                                       
             |_|                                       
             

 "enable_mobile" is enabled but no MOBILE session was found. Do you want to create a MOBILE session (used for AC-4/360RA) [Y/n]? y
 TIDAL: Creating a Mobile session
 TIDAL: Enter your Tidal username and password:
 Username: [my user name]
 Password: [my password]
 Successfully logged in, using MOBILE_DEFAULT token!
 Successfully logged in, using MOBILE_ATMOS token!
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 846, in urlopen
    return self.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 846, in urlopen
    return self.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 846, in urlopen
    return self.urlopen(
  [Previous line repeated 7 more times]
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 836, in urlopen
    retries = retries.increment(method, url, response=response, _pool=self)
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.tidal.com', port=443): Max retries exceeded with url: /v1/albums/?countryCode=DE&limit=9999 (Caused by ResponseError('too many 500 error responses'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/thebrightside/Appdata/Linux-Apps/orpheusdl/orpheus.py", line 223, in <module>
    main()
  File "/home/thebrightside/Appdata/Linux-Apps/orpheusdl/orpheus.py", line 218, in main
    orpheus_core_download(orpheus, media_to_download, tpm, sdm, path)
  File "/home/thebrightside/Appdata/Linux-Apps/orpheusdl/orpheus/core.py", line 397, in orpheus_core_download
    downloader.download_album(media_id, extra_kwargs=media.extra_kwargs)
  File "/home/thebrightside/Appdata/Linux-Apps/orpheusdl/orpheus/music_downloader.py", line 174, in download_album
    album_info: AlbumInfo = self.service.get_album_info(album_id, **extra_kwargs)
  File "/home/thebrightside/Appdata/Linux-Apps/orpheusdl/modules/tidal/interface.py", line 312, in get_album_info
    album_data = self.session.get_album(album_id)
  File "/home/thebrightside/Appdata/Linux-Apps/orpheusdl/modules/tidal/tidal_api.py", line 173, in get_album
    return self._get('albums/' + str(album_id))
  File "/home/thebrightside/Appdata/Linux-Apps/orpheusdl/modules/tidal/tidal_api.py", line 76, in _get
    resp = self.s.get(
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 507, in send
    raise RetryError(e, request=request)
requests.exceptions.RetryError: HTTPSConnectionPool(host='api.tidal.com', port=443): Max retries exceeded with url: /v1/albums/?countryCode=DE&limit=9999 (Caused by ResponseError('too many 500 error responses'))
```

**To Reproduce**
 _Steps to reproduce the behavior:_
 1. Install python3-pip package on Linux Mint 21
 2. Follow install instructions on https://github.com/Dniel97/orpheusdl-tidal
 3. Decide you want orpheusdl in another place and move the install directory
 4. Attempt to archive an album from Tidal

  **Expected behavior**
The album should be saved in the directory set up in the settings.json file.

  **Desktop (please complete the following information):**
  - OS: Linux Mint 21
  - Python version: 3.10.6

  **Additional context**
I never used Python before, so I have no idea what I'm doing. I'm a bit afraid I may have broken the program on step 3, when I moved the installation directory using Nemo, Linux Mint's file manager. However, I don't know how to uninstall or reinstall it. When I type "pip list", orpheusdl doesn't show up among the installed packages at all.

**Comment by Dniel97** [comment]
Have you tried removing the last `/` from the URL? Instead of `https://tidal.com/browse/album/222863872/` try `https://tidal.com/browse/album/222863872`?

**Comment by mrmatteastwood** [comment]
Oh man, that did it. Thanks so much for your quick response!
