### ISSUE TITLE
Bad Subject Token Version

### ISSUE THREAD

**Issue by HoodPharmacist** [Dniel97/orpheusdl-tidal#24]
![Capture](https://user-images.githubusercontent.com/82304192/197118475-263fd3d8-cec1-4729-bb50-02237789421d.JPG)
**Describe the bug**
I have limited knowledge with Python and coding so I am unsure how to solve this one... Im thinking I need to start a new session and update the token? Any help is appreciated! Thank you
 After trying to run orpheus with a link to an album I am met with this error:
              Traceback (most recent call last):
                File "C:\Users\const\orpheusdl\orpheus.py", line 223, in <module>
                  main()
                File "C:\Users\const\orpheusdl\orpheus.py", line 218, in main
                  orpheus_core_download(orpheus, media_to_download, tpm, sdm, path)
                File "C:\Users\const\orpheusdl\orpheus\core.py", line 360, in orpheus_core_download
                  music = orpheus_session.load_module(mainmodule)
                File "C:\Users\const\orpheusdl\orpheus\core.py", line 205, in load_module
                  loaded_module = class_(module_controller)
                File "C:\Users\const\orpheusdl\modules\tidal\interface.py", line 127, in __init__
                  subscription = self.check_subscription(sessions[session_type].get_subscription())
                File "C:\Users\const\orpheusdl\modules\tidal\tidal_api.py", line 339, in get_subscription
                  raise TidalAuthError(r.json()['userMessage'])
              modules.tidal.tidal_api.TidalAuthError: The token has expired. (Bad subject token version)
  **Desktop (please complete the following information):**
  - OS: Windows 10]
  - Python version [3.6.7]

**Comment by Dniel97** [comment]
If the error occurs after waiting for a day, try deleting `config/loginstoragw.bin` to create a new TV (and mobile?) session.

**Comment by HoodPharmacist** [comment]
I waited for a day and deleted the config/loginstoragw.bin and now it's working perfectly! Thank you!
