### ISSUE TITLE
Can't download Hi-Res FLAC files from todays update

### ISSUE THREAD

**Issue by BeachNL** [Dniel97/orpheusdl-tidal#36]
**Describe the bug**
Can't download Hi-Res FLAC files from todays update

**To Reproduce**
Add album link after the command, downloads MQA and not the hi-res 24 bit flac

  **Expected behavior**
Downloads 24 bit FLAC instead of MQA like Tidal said

  **Desktop (please complete the following information):**
  - OS: MacOS
  - Python version 3.9

**Comment by BeachNL** [comment]
I did not, when I try the develop one

Traceback (most recent call last):
  File "/Volumes/Software/Scripts/Python/OrpheusDL/orpheusdlmqa/orpheus.py", line 224, in <module>
    main()
  File "/Volumes/Software/Scripts/Python/OrpheusDL/orpheusdlmqa/orpheus.py", line 37, in main
    orpheus = Orpheus(args.private)
  File "/Volumes/Software/Scripts/Python/OrpheusDL/orpheusdlmqa/orpheus/core.py", line 134, in __init__
    module_information: ModuleInformation = getattr(importlib.import_module(f'modules.{module}.interface'), 'module_information', None)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Volumes/Software/Scripts/Python/OrpheusDL/orpheusdlmqa/modules/tidal/interface.py", line 16, in <module>
    from .mqa_identifier_python.mqa_identifier_python.mqa_identifier import MqaIdentifier
ModuleNotFoundError: No module named 'modules.tidal.mqa_identifier_python.mqa_identifier_python'

**Comment by BeachNL** [comment]
still downloads 16 bit FLACs even on the develop branch

**Comment by BeachNL** [comment]
I tried some from MAX,

Quality is set to hi-fi
last one i tried
https://tidal.com/album/303316291

**Comment by Dniel97** [comment]
You need to update your tokens from the develop branch, so you could copy it manually or just remove the tidal entry from the config/settings.json file. If you already created a session with the old tokens you need to delete loginstorage.bin and create a new mobile session.

**Comment by BeachNL** [comment]
Did wipe my config, now it downloads 24 bit!

**Comment by Dniel97** [comment]
Great to hear, will close this issue then!
