### ISSUE TITLE
Assertion error

### ISSUE THREAD

**Issue by blwckcore** [Dniel97/orpheusdl-tidal#42]
**Describe the bug**
Problems with logging in. Even with disabled mobile session.

**To Reproduce**
 1. Use command 'python orpheus.py search tidal track any'
 2. Choose 'Y'
 3. See error

  **Expected behavior**
Everyting working fine.

  - OS: Windows
  - Python version 3.12.0

  **Additional context**
I've tried to login with VPN and without VPN - nothing changes. Tried different locations with VPN too. Also tried with Python 3.9.13 - same.

```
orpheus.py:12: SyntaxWarning: invalid escape sequence '\ '
  print('''

   ____             _                    _____  _
  / __ \           | |                  |  __ \| |
 | |  | |_ __ _ __ | |__   ___ _   _ ___| |  | | |
 | |  | | '__| '_ \| '_ \ / _ \ | | / __| |  | | |
 | |__| | |  | |_) | | | |  __/ |_| \__ \ |__| | |____
  \____/|_|  | .__/|_| |_|\___|\__,_|___/_____/|______|
             | |
             |_|


DEBUG:root:Orpheus: Modules detected: example, tidal
DEBUG:root:Orpheus: example added as a module
DEBUG:root:Orpheus: tidal added as a module
 "enable_mobile" is enabled but no MOBILE session was found. Do you want to create a MOBILE session (used for AC-4/360RA) [Y/n]? Y
DEBUG:root:TIDAL: No TV session found, creating new one
 TIDAL: Creating a TV session
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): auth.tidal.com:443
DEBUG:urllib3.connectionpool:https://auth.tidal.com:443 "POST /v1/oauth2/device_authorization HTTP/1.1" 200 185
Opening https://link.tidal.com/LTBFV, log in or sign up to TIDAL.
Checking link .....DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): auth.tidal.com:443
DEBUG:urllib3.connectionpool:https://auth.tidal.com:443 "POST /v1/oauth2/token HTTP/1.1" 400 168
.....DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): auth.tidal.com:443
DEBUG:urllib3.connectionpool:https://auth.tidal.com:443 "POST /v1/oauth2/token HTTP/1.1" 400 168
.....DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): auth.tidal.com:443
DEBUG:urllib3.connectionpool:https://auth.tidal.com:443 "POST /v1/oauth2/token HTTP/1.1" 400 168
.....DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): auth.tidal.com:443
DEBUG:urllib3.connectionpool:https://auth.tidal.com:443 "POST /v1/oauth2/token HTTP/1.1" 400 168
.....DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): auth.tidal.com:443
DEBUG:urllib3.connectionpool:https://auth.tidal.com:443 "POST /v1/oauth2/token HTTP/1.1" 400 168
.....DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): auth.tidal.com:443
DEBUG:urllib3.connectionpool:https://auth.tidal.com:443 "POST /v1/oauth2/token HTTP/1.1" 200 None

Successfully linked!
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.tidal.com:443
DEBUG:urllib3.connectionpool:https://api.tidal.com:443 "GET /v1/sessions HTTP/1.1" 403 919
Traceback (most recent call last):
  File "C:\Users\blwckcore\Desktop\orpheus\OrpheusDL\orpheus.py", line 224, in <module>
    main()
  File "C:\Users\blwckcore\Desktop\orpheus\OrpheusDL\orpheus.py", line 113, in main
    module = orpheus.load_module(modulename)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\blwckcore\Desktop\orpheus\OrpheusDL\orpheus\core.py", line 210, in load_module
    loaded_module = class_(module_controller)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\blwckcore\Desktop\orpheus\OrpheusDL\modules\tidal\interface.py", line 106, in __init__
    sessions[session_type].auth()
  File "C:\Users\blwckcore\Desktop\orpheus\OrpheusDL\modules\tidal\tidal_api.py", line 556, in auth
    assert (r.status_code == 200)
AssertionError
```

**Comment by blwckcore** [comment]
I was using bad VPN that doesn't hide my IP as it should. Because I live in Russia, Tidal is blocked so I need to use VPN. It'll be good if you add option to use proxy in your module somehow.
