### ISSUE TITLE
modules.tidal.tidal_api.TidalAuthError: The token has expired. (Expired on time)

### ISSUE THREAD

**Issue by seanluommd** [Dniel97/orpheusdl-tidal#75]
Traceback (most recent call last):
  File "F:\orpheusdl\orpheus.py", line 226, in <module>
    main()
  File "F:\orpheusdl\orpheus.py", line 221, in main
    orpheus_core_download(orpheus, media_to_download, tpm, sdm, path)
  File "F:\orpheusdl\orpheus\core.py", line 368, in orpheus_core_download
    music = orpheus_session.load_module(mainmodule)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\orpheusdl\orpheus\core.py", line 210, in load_module
    loaded_module = class_(module_controller)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\orpheusdl\modules\tidal\interface.py", line 136, in __init__
    subscription = self.check_subscription(sessions[session_type].get_subscription())
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\orpheusdl\modules\tidal\tidal_api.py", line 288, in get_subscription
    raise TidalAuthError(r.json()['userMessage'])
modules.tidal.tidal_api.TidalAuthError: The token has expired. (Expired on time)

**Comment by lopes143** [comment]
This is still happening to me, and I have everything updated
