### ISSUE TITLE
Login error

### ISSUE THREAD

**Issue by marcobibichan** [Dniel97/orpheusdl-tidal#77]
**Describe the bug**

**To Reproduce**
 1. Use command '...'
 2. Choose '....' (only needed for search)
 3. See error

  **Expected behavior**

  **Screenshots**
 If applicable, add screenshots to help explain your problem or to show the error message.

  **Desktop (please complete the following information):**
  - OS: [e.g. Windows, Unix, Android]
  - Python version [e.g. 3.6.9, 3.9.3]

  **Additional context**

After I get the Tidal Token from the web that maybe correct, I run python3 orpheus.py https://tidal.com/track/337501973?u and trying to log in, I get the following respond:

Traceback (most recent call last):
  File "/storage/emulated/0/OrpheusDL/orpheus.py", line 225, in <module>
    main()
  File "/storage/emulated/0/OrpheusDL/orpheus.py", line 220, in main
    orpheus_core_download(orpheus, media_to_download, tpm, sdm, path)
  File "/storage/emulated/0/OrpheusDL/orpheus/core.py", line 368, in orpheus_core_download
    music = orpheus_session.load_module(mainmodule)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/storage/emulated/0/OrpheusDL/orpheus/core.py", line 210, in load_module
    loaded_module = class_(module_controller)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/storage/emulated/0/OrpheusDL/modules/tidal/interface.py", line 113, in __init__
    login_session = auth_and_save_session(self.init_session(login_session_type), login_session_type)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/storage/emulated/0/OrpheusDL/modules/tidal/interface.py", line 83, in auth_and_save_session
    session = self.auth_session(session, session_type, login_session)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/storage/emulated/0/OrpheusDL/modules/tidal/interface.py", line 188, in auth_session
    session.auth(username, password)
  File "/storage/emulated/0/OrpheusDL/modules/tidal/tidal_api.py", line 359, in auth
    raise TidalAuthError("TIDAL BOT protection, try again later!")
modules.tidal.tidal_api.TidalAuthError: TIDAL BOT protection, try again later!

![Screenshot_20241226_202125_com_termux_TermuxActivity](https://github.com/user-attachments/assets/d1671560-ef71-4021-890d-7fe75ac63f70)

**Comment by Dniel97** [comment]
Just use the provided tokens and properly fill the template next time.
